#+POSTID: 1886
#+DATE: [2012-08-08 Wed 11:29]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: blogs
#+TAGS: linux, git, github, git branch -M
#+DESCRIPTION: procedure to safely rename git's master branch to some other name
#+TITLE: Rename master branch in git

There may be situation where one has to rename master branch to
something else. Consider the situation where I have =master= branch as
default branch. I have two more branches, =ics= and =froyo= apart from
master, but I want to rename my =master= branch to =ics=.

*** *Rename the =master= branch to =ics=*

#+BEGIN_SRC bash
git branch -M -a master ics
#+END_SRC

*-M* will rename the branch even if the new branch name already exists.

*** *also remove =master= branch from remote.*

#+BEGIN_SRC bash
git push origin :master
#+END_SRC

To set the default branch as =ics= on github, visit the 'repository'
section and go to the =Admin= tab. In =Settings= change the =Default=
branch from =master= to =ics=.

*** *Tips*
    1. *to clone specific branch from git repository*
       #+BEGIN_SRC bash
       git clone -b BRANCH_NAME git@github.com:USER/REPOSITORY.git
       #+END_SRC

       for example,

       #+BEGIN_SRC bash
       git clone -b my-branch git@github.com:androportal/installer.git
       #+END_SRC

    2. *copy file from another branch*
       #+BEGIN_SRC bash
       git co BRANCH_NAME FILE
       #+END_SRC

       for example,
       #+BEGIN_SRC bash
       git co froyo html2sphinx.sh
       #+END_SRC

    3. *checkout particular branch from remotes*
       #+BEGIN_SRC bash
       git co -b BRANCH remotes/origin/BRANCH
       #+END_SRC

       for example,
       #+BEGIN_SRC bash
       git co -b froyo remotes/origin/froyo
       #+END_SRC

    4. *remove files from git which are already deleted from system*
       #+BEGIN_SRC bash
       for file in $(git ls-files --deleted); do git rm $file; done
       #+END_SRC
